### ISSUE TITLE
Reduce size of Docker image

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/pfps-shopping-cart#19]
Right now, the generated Docker image has 541 MBs of size, which is quite big. 

Let's try to reduce it...

**Comment by calvinlfer** [comment]
Hey @gvolpe, I managed to set `dockerBaseImage := "azul/zulu-openjdk-alpine:8"` and enabling the `AshScriptPlugin` to allow for alpine based images reduces the size to 105 MB. However, the following key causes an NPE (since I don't have these set in my shell):

```scala
    dockerEnvVars ++= Map(
      "SC_APP_ENV" -> System.getenv("SC_APP_ENV"),
      "SC_JWT_CLAIM" -> System.getenv("SC_JWT_CLAIM"),
      "SC_JWT_SECRET_KEY" -> System.getenv("SC_JWT_SECRET_KEY"),
      "SC_PASSWORD_SALT" -> System.getenv("SC_PASSWORD_SALT"),
      "SC_ACCESS_TOKEN_SECRET_KEY" -> System.getenv("SC_ACCESS_TOKEN_SECRET_KEY"),
      "SC_ADMIN_USER_TOKEN" -> System.getenv("SC_ADMIN_USER_TOKEN")
    ),
```
So I removed it and I was able to build and run the container.

Is there any reason why these are explicitly specified? as should just be able to feed in the environment variables via docker run or compose

**Comment by gvolpe** [comment]
No particular reason @calvinlfer , I actually need to come back to this once I start working on Chapter 9. 

Last evening, there was another talk in the local Scala meetup (in Spanish) exactly about this, so I have some material :) https://slides.com/hugobellomusto/dockerizando-mi-scala-app#/
